### ISSUE TITLE
Hard-coded wp-content folder

### ISSUE THREAD

**Issue by edlefebvre** [myflyingbox/woocommerce-plugin#15]
The content folder of WordPress can be changed via options.

It causes a problem because wp-content is hard-coded here:

`my-flying-box/includes/class-my-flying-box.php`

On line 668:
`wp_enqueue_script( 'mfb_delivery_locations','/wp-content/plugins/my-flying-box/assets/js/delivery_locations.js',array( 'jquery', 'google-api-grouped' ) );`

It should be:

`wp_enqueue_script( 'mfb_delivery_locations', plugins_url().'/my-flying-box/assets/js/delivery_locations.js',array( 'jquery', 'google-api-grouped' ) );`

**Comment by tbelliard** [comment]
Thanks for the report! This is now fixed and will be included in the next release.
